/*** Generated by streamline 0.10.15 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var f;

  f = function f__1(_) { var __frame = { name: "f__1", line: 4 }; return __func(_, this, arguments, f__1, 0, __frame, function __$f__1() {
      return setTimeout(__cb(_, __frame, 1, 11, _, true), 2000); }); };


  f(function(err) {
    return console.log("This took 2 seconds in _coffee"); });


}).call(this);
