/*** Generated by streamline 0.10.15 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func; (function() {
  var foobar;

  foobar = function foobar__1(_) { var a; var __frame = { name: "foobar__1", line: 4 }; return __func(_, this, arguments, foobar__1, 0, __frame, function __$foobar__1() {

      a = (1 + 1); _(); }); };


  foobar(function(err) {  });

}).call(this);
