/*** Generated by streamline 0.10.13 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb,__catch=__rt.__catch,__tryCatch=__rt.__tryCatch; var fs = require("fs");

var bar = function bar__1(_) { var __frame = { name: "bar__1", line: 3 }; return __func(_, this, arguments, bar__1, 0, __frame, function __$bar__1() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$bar__1() {

          return fs.stat("./", __cb(_, __frame, 2, 18, function ___(__0, __1) { stat = __1; __then(); }, true)); }); })(function ___(err, __result) { __catch(function __$bar__1() { if (err) {

            return _(err); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, function __$bar__1() { _(); }); }); });};



bar(function(err, stats) {
  console.log(("These are the stats " + stats));});
