/*** Generated by streamline 0.10.13 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func; (function() {
  var foo;

  foo = function foo__1(_) { var __frame = { name: "foo__1", line: 4 }; return __func(_, this, arguments, foo__1, 0, __frame, function __$foo__1() {
      return _(null, console.log("Hey, I'm in streamline!")); }); };


  foo(function(err) {
    return console.log("Hey, I'm done running!"); });


}).call(this);
